language: generic
services: docker

env:
  global:
    - NAME=node-mongo
    - CACHE_FOLDER=$HOME/docker-images
    - CACHE_FILE=${CACHE_FOLDER}/${NAME}-${TRAVIS_COMMIT}.tgz

before_install:
- openssl aes-256-cbc -K $encrypted_46351ee82ac2_key -iv $encrypted_46351ee82ac2_iv -in .env.enc -out .env -d
- VERSION="0.1.4"
- wget https://github.com/knqyf263/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
- tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz

jobs:
  include:
  - stage: Nodejsscan of code 
    install: 
      - virtualenv venv && . ./venv/bin/activate 
      - pip install nodejsscan
      - nodejsscan -f index.js && nodejsscan -d models
      - nodejsscan -d routes && nodejsscan -d test

  - stage: build the Docker image for testing        
    script: 
      - npm run build
      - mkdir -p ${CACHE_FOLDER}
      - docker save docker_backend | gzip -c > ${CACHE_FILE}

  - stage: Run unit, integration tests and scan the docker image
    script: 
      - if [[ -f ${CACHE_FILE} ]]; then docker load -i ${CACHE_FILE}; fi
      - npm test
      - ./trivy --exit-code 1 --severity CRITICAL --quiet docker_backend

  - stage: Push image to private docker registry
    after_success:
      - if [[ -f ${CACHE_FILE} ]]; then docker load -i ${CACHE_FILE}; fi
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - export REPO=kottapar/myrepo
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker tag docker_backend:latest ${REPO}:${TAG}
      - docker tag docker_backend:latest ${REPO}:${COMMIT}
      - docker push ${REPO}

cache:
  bundler: true
  directories:
    - ${CACHE_FOLDER}

