services: docker

before_install:
- openssl aes-256-cbc -K $encrypted_46351ee82ac2_key -iv $encrypted_46351ee82ac2_iv 
  -in .env.enc -out .env -d

jobs:
  include:
  - stage: build the Docker image
    install: npm run build

  - stage: Run unit and integration tests
    script: npm test
